# This is a basic workflow to help you get started with Actions
# - 使用 [telegram-action](https://github.com/appleboy/telegram-action)
#   - 參考使用 API Input variables
# - 頁面 https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
#   - 參考可放在message中的object
# - 頁面 https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues
#   - 參考 issue 有幾種狀態
# - 頁面 https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#   - 參考 workflow syntax 寫法
# - 頁面 https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions
#   - 參考 可用於 ${{}} 內的函數, 例如 toJSON

name: TELEGRAM

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, reopened]
  project_card:
    types: [created]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#       - name: custom message push
#         if: ${{ github.event_name == 'push' }}
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: html
#           disable_web_page_preview: true
#           message: <a href="${{github.event.sender.html_url}}">${{github.actor}}</a>
#             於 <a href="${{github.event.repository.html_url}}">${{github.event.repository.name}}</a>
#             做了<a href="${{github.event.commits[0].url}}">${{github.event.commits[0].message}}</a>
#       - name: custom message issues
#         if: ${{ github.event_name == 'issues' }}
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: html
#           disable_web_page_preview: true
#           message: <a href="${{github.event.sender.html_url}}">${{github.actor}}</a>
#             於 <a href="${{github.event.repository.html_url}}">${{github.event.repository.name}}</a>
#             ${{github.event.action}} issue <a href="${{github.event.issue.html_url}}">${{github.event.issue.title}}</a>
#       - name: custom message project_card
#         if: ${{ github.event_name == 'project_card' }}
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: html
#           disable_web_page_preview: true
#           message: <a href="${{github.event.sender.html_url}}">${{github.actor}}</a>
#             於 <a href="${{github.event.repository.html_url}}">${{github.event.repository.name}}</a>
#             <a href="https://github.com/t1ina2003/ectrade_bot_new/projects/1">專案</a> ${{github.event.action}} item 
#       - name: custom message pull_request
#         if: ${{ github.event_name == 'pull_request' }}
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: html
#           disable_web_page_preview: true
#           message: <a href="${{github.event.sender.html_url}}">${{github.actor}}</a>
#             於 <a href="${{github.event.repository.html_url}}">${{github.event.repository.name}}</a>
#             ${{github.event.action}} pull_request <a href="${{github.event.pull_request.html_url}}">${{github.event.pull_request.title}}</a>
